version: '3.8'

services:

  blogify.blogging:
    container_name: 'Blogify.Blogging'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: src\Services\Blogging\Blogging.Api/Dockerfile
    ports:
      - "5006:5006"
    depends_on:
      - "postgres"
    networks:
      - aspnetcoreapp-network

  blogging.db:
    container_name: 'Blogging.DB'
    image: postgres:14.1
    environment:
      # change this for a "real" app!
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    networks:
      - aspnetcoreapp-network

  blogify.identity:
    container_name: 'Blogify.Identity'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: src\Services\Blogging\Blogging.Api/Dockerfile
    ports:
      - "5007:5006"
    depends_on:
      - "postgres"
    networks:
      - aspnetcoreapp-network

  identity.db:
    container_name: 'Identity.DB'
    image: postgres:14.1
    environment:
      # change this for a "real" app!
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5439:5432'
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge